{
 "title": "libp2p Identify",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Identify Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(libp2p_identify_identify_total[$__rate_interval])",
     "legendFormat": "{{dir}}"
    }
   ]
  },
  {
   "title": "Identify Push Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(libp2p_identify_identify_push_total[$__rate_interval])",
     "legendFormat": "{{dir}}"
    }
   ]
  },
  {
   "title": "Pushes triggered",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(libp2p_identify_identify_pushes_triggered_total[$__rate_interval])",
     "legendFormat": "{{trigger}}"
    }
   ]
  }
 ]
}